# Generated by Django 4.2 on 2024-03-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='image',
        ),
        migrations.AddField(
            model_name='record',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
