# Generated by Django 4.0.5 on 2024-03-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_record_image_record_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(verbose_name='Date Created')),
                ('time_created', models.TimeField(verbose_name='Time Created')),
                ('day_of_week', models.CharField(max_length=20, verbose_name='Day of the Week')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='webapp.record')),
            ],
        ),
    ]
