# Generated by Django 4.0.5 on 2024-03-17 07:52

import datetime
from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_recordadditionalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordadditionalinfo',
            name='record',
        ),
        migrations.AddField(
            model_name='recordadditionalinfo',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='recordadditionalinfo',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='recordadditionalinfo',
            name='national_id',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='recordadditionalinfo',
            name='picture',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='day_of_week',
            field=models.CharField(default='', max_length=20, verbose_name='Day of the Week'),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='time_created',
            field=models.TimeField(default=webapp.models.get_current_time, verbose_name='Time Created'),
        ),
    ]
