# Generated by Django 4.0.5 on 2024-03-22 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_recordadditionalinfo_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordadditionalinfo',
            name='record',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='webapp.record'),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='date_created',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='national_id',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='picture',
            field=models.ImageField(default='', upload_to='additional_info/images/'),
        ),
        migrations.AlterUniqueTogether(
            name='recordadditionalinfo',
            unique_together={('national_id', 'date_created')},
        ),
    ]
