# Generated by Django 4.0.5 on 2024-03-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_recordadditionalinfo_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordadditionalinfo',
            name='record',
        ),
    ]
