# Generated by Django 4.0.5 on 2024-03-23 10:56

import datetime
from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_recordadditionalinfo_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='date_created',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='time_created',
            field=models.TimeField(default=webapp.models.get_current_time, unique=True, verbose_name='Time Created'),
        ),
    ]
