# Generated by Django 4.0.5 on 2024-03-23 11:09

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_recordadditionalinfo_date_created_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordadditionalinfo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='time_created',
            field=models.TimeField(default=webapp.models.get_current_time, verbose_name='Time Created'),
        ),
    ]
