# Generated by Django 4.0.5 on 2024-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_recordadditionalinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordadditionalinfo',
            name='national_id',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
